### ISSUE TITLE
Informational: the intro videos can also be skipped by passing a command line argument to the binary

### ISSUE THREAD

**Issue by Sipu** [Lyall/GreatCircleFix#6]
The intro skip can be done with +com_skipIntroVideo 1 command-line argument to the game executable through game launch options in steam so the hook in this library is not required.

**Comment by Lyall** [comment]
Yes I'm well aware of this command-line argument. The skip intro hook sets the same flag that having "+com_skipIntroVideo 1" as a command-line argument will. It still has its use for people that don't know about this and those using the Xbox version as it does not easily allow you to change command-line arguments.
